version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env  # Specify the .env file
    networks:
      - mynetwork  # Assign the app service to the mynetwork network
    command: ["dockerize", "-wait", "tcp://db:3306", "-timeout", "60s", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    env_file:
      - .env  # Specify the path to your .env file
    volumes:
      - mysql_data:/var/lib/mysql  # Named volume for MySQL data
    networks:
      - mynetwork  # Assign the app service to the mynetwork network

volumes:
  mysql_data:  # Define the named volume here

networks:
  mynetwork:

